name: CLANG build ARM64

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: git-for-windows/setup-git-for-windows-sdk@v1
        with:
          flavor: makepkg-git
          architecture: aarch64
          # This assumes that the job is running on a self-hosted runner,
          # in which case we need to cleanup SDK files.
          cleanup: true
      - name: Build Git CLANGARM64
        run: make -j`nproc`
